import "./globals.css";
import { Space_Mono } from "next/font/google";

const space_Mono = Space_Mono({ subsets: ["latin"], weight:['400','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={space_Mono.className}>
        <main className="bg-emerald-100 h-screen flex items-center justify-center">
          <div className="max-w-screen-md w-full mx-auto grid flex-1 flex-col px-4">
            <div className="bg-white rounded-2xl shadow-lg w-full p-8">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
